### ISSUE TITLE
how can i get the username and password for login page

### ISSUE THREAD

**Issue by nikitaroy316** [samarth-p/College-ERP#1]
hey can you tell me the username and password to access the page.

**Comment by samarth-p** [comment]
The login page is common for students and teachers.
The username is their name and password for everyone is 'project123'.
Example usernames:
student- 'samarth'
teacher- 'trisila'

Also, you can access the django admin page with username 'admin' and the above password.
I will make a readme page soon with more details

**Comment by nikitaroy316** [comment]
thanks a lot!!

**Comment by shravi2624** [comment]
How i can add Students and teachers in it?

**Comment by samarth-p** [comment]
You can change students, teachers and other details in the django admin page

**Comment by shravi2624** [comment]
Can you please tell me that which djangi version you use in it?

**Comment by samarth-p** [comment]
django version 2.1.3

**Comment by ranjannayan** [comment]
when i enter the credentials for the admin, it leads me to logout page. Can u help me resolve this
