### ISSUE TITLE
Admin page login loop

### ISSUE THREAD

**Issue by Anjan112** [samarth-p/College-ERP#11]
https://user-images.githubusercontent.com/77722979/111449590-8b004800-8735-11eb-91ad-ade8be84de16.mp4

The admin page seems to loop back to the logout page in spite of logging in (This happened when I clicked on the visit page link)

**Comment by samarth-p** [comment]
The admin user can only login to the django admin page currently. The users usually have a teacher or student attribute. Since, admin user has neither, I think it directly logs you out.

**Comment by Anjan112** [comment]
Since its a broken link can you remove it.
I have suggested a sample code below...


Code:
from django.contrib import admin
from myapp.models import MyModel

class MyModelAdmin(admin.ModelAdmin):
    view_on_site = False

admin.site.register(MyModel,MyModelAdmin)


Can you consider removing it??

**Comment by samarth-p** [comment]
You can create a pull request for this.

**Comment by Anjan112** [comment]
I have created a pull request. 
Please accept it.

**Comment by samarth-p** [comment]
I have merged it. Thanks for contributing!

**Comment by Anjan112** [comment]
Thanks a lot, bro!! Great work..
