### ISSUE TITLE
ModuleNotFoundError: No module named 'rest_framework'

### ISSUE THREAD

**Issue by Codewith-ARK** [samarth-p/College-ERP#32]
I get the following error message when I run the dev server

![image](https://github.com/samarth-p/College-ERP/assets/89801934/23cd446d-2393-4472-9f3e-88a30840b809)

**Comment by TharunBalaji2004** [comment]
@Codewith-ARK Encountered the same issue, solved it by installing all packages mentioned in requirements.txt

Just run this command `pip install -r requirements.txt` in main project directory
