### ISSUE TITLE
Issue in student - Timetable page

### ISSUE THREAD

**Issue by zakeerms** [samarth-p/College-ERP#4]
I got an error in this page
MultipleObjectsReturned at /info/student/CS3A/timetable/

Kindly help me to fix this issue
-------------------------------------------------------------------------------------

Request Method: | GET
-- | --
http://127.0.0.1:8000/info/student/CS3A/timetable/
2.2.6
MultipleObjectsReturned
get() returned more than one AssignTime -- it returned 2!
C:\Program Files\Anaconda3\lib\site-packages\django\db\models\query.py in get, line 412
C:\Program Files\Anaconda3\python.exe
3.6.0
['E:\\SVN\\Python\\SourceCode\\SAU-ERP',  'C:\\Program Files\\Anaconda3\\python36.zip',  'C:\\Program Files\\Anaconda3\\DLLs',  'C:\\Program Files\\Anaconda3\\lib',  'C:\\Program Files\\Anaconda3',  'C:\\Users\\zakee\\AppData\\Roaming\\Python\\Python36\\site-packages',  'C:\\Program Files\\Anaconda3\\lib\\site-packages',  'C:\\Program Files\\Anaconda3\\lib\\site-packages\\Sphinx-1.5.1-py3.6.egg',  'C:\\Program Files\\Anaconda3\\lib\\site-packages\\win32',  'C:\\Program Files\\Anaconda3\\lib\\site-packages\\win32\\lib',  'C:\\Program Files\\Anaconda3\\lib\\site-packages\\Pythonwin',  'C:\\Program '  'Files\\Anaconda3\\lib\\site-packages\\setuptools-27.2.0-py3.6.egg']
Sat, 9 Nov 2019 02:44:19 +0000
-------------------------------------------------------------------
for j in range(12):
            if j == 0:
                matrix[i][0] = d[0]
                continue
            if j == 4 or j == 8:
                continue
            try:
                a = asst.get(period=time_slots[t][0], day=d[0]) 
…
                matrix[i][j] = a.assign.course_id
            except AssignTime.DoesNotExist:
                pass
            t += 1

    context = {'matrix': matrix}
----------------------------------------------------------------
error in this python file, info\views.py in timetable
line number 219,

 a = asst.get(period=time_slots[t][0], day=d[0]) 

![error1](https://user-images.githubusercontent.com/16174872/68521693-2b547b80-0269-11ea-9dfd-c248f15deb4f.PNG)
![error2](https://user-images.githubusercontent.com/16174872/68521706-563ecf80-0269-11ea-89a8-6d1cb188bd14.PNG)

**Comment by samarth-p** [comment]
I have modified the sqlite3 file and it should work now.

There was an error because two classes were assigned to the same time slot.

**Comment by zakeerms** [comment]
Thanks bro, Great Job you have done :), Let me know your contact details.

**Comment by samarth-p** [comment]
Thanks a lot! You contact me through my email samarthp1@gmail.com

**Comment by zakeerms** [comment]
I sent an email, please check.

**Comment by arish1000** [comment]
While running this project with MSSQL database connection, I got an error saying:
"django.db.utils.ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid object name 'info_user'. (208) (SQLExecDirectW); [42S02] [Microsoft
][ODBC Driver 11 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")
[18/May/2020 19:13:24] "POST /accounts/login/?next=/ HTTP/1.1" 500 215879"

Can you please help me out to get it resolved?

**Comment by Nan-Has** [comment]
Bonjour à tous! Je me tracasse depuis deux jours avec ce même projet, j'espère vraiment trouver satisfaction ici aussi. Voici mon souci en capture d'écran
![Capture d’écran de 2022-05-04 00-19-40](https://user-images.githubusercontent.com/93581281/166588520-14413e66-7d0d-4b3d-8d61-3058676cb144.png)
![Capture d’écran de 2022-05-04 00-19-55](https://user-images.githubusercontent.com/93581281/166588551-6f71ac55-2857-4b8c-ad7b-2e00cb75be2d.png)
