### ISSUE TITLE
regarding time change

### ISSUE THREAD

**Issue by patelyash1924** [samarth-p/College-ERP#9]
how can i change time(year) in attendance section?
It's show 2018 which i want to change in 2020.
please help

**Comment by Aish026** [comment]
did u got the answer??if yes please tell me too

**Comment by patelyash1924** [comment]
not yet..

**Comment by Aish026** [comment]
okay let me know if you get it....thank you

**Comment by patelyash1924** [comment]
sure.

**Comment by thanijay** [comment]
did anyone get the answer?

**Comment by samarth-p** [comment]
Sorry for the late response. I have added a method to change the attendance timerange in the admin page. Please check Readme for more details.

**Comment by patelyash1924** [comment]
Thank you.
